export default {
  buddha1: require('../assets/images/BuddhaImage-3.gif'),
  buddha: require('../assets/images/buddha.png'),
  wheel: require('../assets/images/dhamma-wheel.png'),
  dhamma_wheel: require('../assets/images/dhamma.png'),
  dhamma_1: require('../assets/images/phaauk.jpeg'),
  dhamma_2: require('../assets/images/venNDML.jpeg'),
  dhamma_3: require('../assets/images/thidagu.jpeg'),
  dhamma_4: require('../assets/images/kyarNiKan.jpeg'),
  dhamma_5: require('../assets/images/delohh.jpeg'),
  dhamma_6: require('../assets/images/phyu.jpeg'),
  dhamma_7: require('../assets/images/uztk.jpg'),
  dhamma_8: require('../assets/images/tsss.jpeg'),
  dhamma_9: require('../assets/images/cmrm.jpeg'),
  dhamma_10: require('../assets/images/maharKan.jpeg'),
  dhamma_11: require('../assets/images/minKon.jpeg'),
};
